export const mockPlaylists = [
  {
    id: "1",
    name: "Tus me gusta",
    description: "Tus canciones favoritas",
    images: [{ url: "/purple-heart-gradient.jpg" }],
    tracks: { total: 234 },
    owner: { display_name: "Christian Velasco" },
  },
  {
    id: "2",
    name: "The Eminem Show",
    description: "Eminem",
    images: [{ url: "/eminem-album-cover.jpg" }],
    tracks: { total: 20 },
    owner: { display_name: "Eminem" },
  },
  {
    id: "3",
    name: "Cartel De Santa",
    description: "Hip Hop en Español",
    images: [{ url: "/cartel-de-santa-album.jpg" }],
    tracks: { total: 15 },
    owner: { display_name: "Cartel De Santa" },
  },
  {
    id: "4",
    name: "Everythanga Corrupt",
    description: "Ice Cube",
    images: [{ url: "/ice-cube-album.jpg" }],
    tracks: { total: 18 },
    owner: { display_name: "Ice Cube" },
  },
  {
    id: "5",
    name: "Música Clásica Que Sí Es Clásica",
    description: "Las mejores obras clásicas",
    images: [{ url: "/classical-music-beethoven.jpg" }],
    tracks: { total: 50 },
    owner: { display_name: "Spotify" },
  },
  {
    id: "6",
    name: "Beethoven's Best Piano Songs",
    description: "Piano clásico",
    images: [{ url: "/beethoven-piano.jpg" }],
    tracks: { total: 30 },
    owner: { display_name: "Spotify" },
  },
  {
    id: "7",
    name: "2001",
    description: "Dr. Dre",
    images: [{ url: "/dr-dre-2001-album.jpg" }],
    tracks: { total: 22 },
    owner: { display_name: "Dr. Dre" },
  },
  {
    id: "8",
    name: "2Pac, Pop Smoke - Write This Down",
    description: "Hip Hop Mix",
    images: [{ url: "/2pac-pop-smoke.jpg" }],
    tracks: { total: 25 },
    owner: { display_name: "Spotify" },
  },
]

export const mockDailyMixes = [
  {
    id: "mix1",
    name: "Mix diario 1",
    description: "Tu atraco a joyas ocultas, recomendaciones y más",
    images: [{ url: "/abstract-pink-geometric-pattern.jpg" }],
    tracks: { total: 50 },
    owner: { display_name: "Spotify" },
  },
  {
    id: "mix2",
    name: "Mix diario 2",
    description: "Apretasen, Hando, Ludovico Einaudi y más",
    images: [{ url: "/blue-abstract-music.jpg" }],
    tracks: { total: 50 },
    owner: { display_name: "Spotify" },
  },
  {
    id: "mix3",
    name: "Mix diario 3",
    description: "Dr. Dre, 2Pac, Ice Cube y más",
    images: [{ url: "/red-hip-hop-urban.jpg" }],
    tracks: { total: 50 },
    owner: { display_name: "Spotify" },
  },
  {
    id: "mix4",
    name: "Mix diario 4",
    description: "Snoop Dogg, Nipsey Hussle, Drakeo the Ruler y más",
    images: [{ url: "/pink-urban-music.jpg" }],
    tracks: { total: 50 },
    owner: { display_name: "Spotify" },
  },
  {
    id: "mix5",
    name: "Mix diario 5",
    description: "David Guetta, Tiësto, Castor & Pollux y más",
    images: [{ url: "/green-electronic-music.jpg" }],
    tracks: { total: 50 },
    owner: { display_name: "Spotify" },
  },
  {
    id: "mix6",
    name: "Mix diario 6",
    description: "KISS, Queen, Guns N' Roses y más",
    images: [{ url: "/purple-rock-music.jpg" }],
    tracks: { total: 50 },
    owner: { display_name: "Spotify" },
  },
]

export const mockRecentlyPlayed = [
  {
    id: "recent1",
    name: "Tus me gusta",
    description: "234 canciones",
    images: [{ url: "/purple-heart-liked-songs.jpg" }],
    tracks: { total: 234 },
    owner: { display_name: "Christian Velasco" },
  },
  {
    id: "recent2",
    name: "The Eminem Show",
    description: "Eminem",
    images: [{ url: "/eminem-show-album.jpg" }],
    tracks: { total: 20 },
    owner: { display_name: "Eminem" },
  },
  {
    id: "recent3",
    name: "BEST OF MOZART",
    description: "Wolfgang Amadeus Mozart",
    images: [{ url: "/mozart-classical-portrait.jpg" }],
    tracks: { total: 100 },
    owner: { display_name: "Spotify" },
  },
  {
    id: "recent4",
    name: "Everythanga Corrupt",
    description: "Ice Cube",
    images: [{ url: "/ice-cube-corrupt.jpg" }],
    tracks: { total: 18 },
    owner: { display_name: "Ice Cube" },
  },
  {
    id: "recent5",
    name: "The London Symphony Orchestra",
    description: "Top 100 Classical",
    images: [{ url: "/placeholder.svg?height=300&width=300" }],
    tracks: { total: 100 },
    owner: { display_name: "Spotify" },
  },
  {
    id: "recent6",
    name: "GYM pesado y al fallo",
    description: "NO PAIN NO GAIN",
    images: [{ url: "/placeholder.svg?height=300&width=300" }],
    tracks: { total: 45 },
    owner: { display_name: "david_vina32" },
  },
]

export const mockBackToYourMusic = [
  {
    id: "back1",
    name: "GYM pesado y al fallo",
    description: "NO PAIN NO GAIN",
    images: [{ url: "/gym-workout-motivation.jpg" }],
    tracks: { total: 45 },
    owner: { display_name: "david_vina32" },
  },
  {
    id: "back2",
    name: "Millonario Yo",
    description: "Millonario & W. Corona",
    images: [{ url: "/millonario-mexican-hip-hop-album-cover.jpg" }],
    tracks: { total: 12 },
    owner: { display_name: "Millonario" },
  },
  {
    id: "back3",
    name: "Paranoid",
    description: "Black Sabbath",
    images: [{ url: "/black-sabbath-paranoid-album-cover.jpg" }],
    tracks: { total: 8 },
    owner: { display_name: "Black Sabbath" },
  },
  {
    id: "back4",
    name: "Melodías Para Leer",
    description: "Música clásica relajante",
    images: [{ url: "/classical-music-reading-relaxing.jpg" }],
    tracks: { total: 60 },
    owner: { display_name: "Spotify" },
  },
  {
    id: "back5",
    name: "BEST OF MOZART",
    description: "Lo mejor de radio This Is WOLFGANG AMADEUS MOZART",
    images: [{ url: "/mozart-classical-composer-portrait.jpg" }],
    tracks: { total: 100 },
    owner: { display_name: "Spotify" },
  },
  {
    id: "back6",
    name: "Los Auténticos Decadentes",
    description: "Los Auténticos Decadentes - 25 Años",
    images: [{ url: "/los-autenticos-decadentes-band.jpg" }],
    tracks: { total: 30 },
    owner: { display_name: "Los Auténticos Decadentes" },
  },
  {
    id: "back7",
    name: "Party Rock",
    description: "LMFAO",
    images: [{ url: "/lmfao-party-rock-album.jpg" }],
    tracks: { total: 10 },
    owner: { display_name: "LMFAO" },
  },
  {
    id: "back8",
    name: "Empire Of The Sun",
    description: "Artists",
    images: [{ url: "/empire-of-the-sun-band.jpg" }],
    tracks: { total: 50 },
    owner: { display_name: "Empire Of The Sun" },
  },
  {
    id: "back9",
    name: "Rule the World (Everybody)",
    description: "Tiësto, Tears For Fears, NIIKO X SWAE",
    images: [{ url: "/tiesto-edm-electronic-music.jpg" }],
    tracks: { total: 1 },
    owner: { display_name: "Tiësto" },
  },
  {
    id: "back10",
    name: "LECTURA Y CALMA",
    description: "Música para leer",
    images: [{ url: "/calm-reading-music-peaceful.jpg" }],
    tracks: { total: 75 },
    owner: { display_name: "Spotify" },
  },
]

export const mockTracks = [
  {
    id: "track1",
    name: "Hello (feat. Dragonette)",
    artists: [{ name: "Martin Solveig" }, { name: "Dragonette" }],
    album: {
      name: "Hello",
      images: [{ url: "/martin-solveig-hello-album-cover.jpg" }],
    },
    duration_ms: 211000,
    uri: "spotify:track:1",
    preview_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    liked: true,
  },
  {
    id: "track2",
    name: "Without Me",
    artists: [{ name: "Eminem" }],
    album: {
      name: "The Eminem Show",
      images: [{ url: "/eminem-album-cover.jpg" }],
    },
    duration_ms: 290000,
    uri: "spotify:track:2",
    preview_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    liked: true,
  },
  {
    id: "track3",
    name: "Till I Collapse",
    artists: [{ name: "Eminem" }, { name: "Nate Dogg" }],
    album: {
      name: "The Eminem Show",
      images: [{ url: "/eminem-album-cover.jpg" }],
    },
    duration_ms: 297000,
    uri: "spotify:track:3",
    preview_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    liked: true,
  },
  {
    id: "track4",
    name: "Cleanin' Out My Closet",
    artists: [{ name: "Eminem" }],
    album: {
      name: "The Eminem Show",
      images: [{ url: "/eminem-album-cover.jpg" }],
    },
    duration_ms: 298000,
    uri: "spotify:track:4",
    preview_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    liked: true,
  },
  {
    id: "track5",
    name: "Superman",
    artists: [{ name: "Eminem" }, { name: "Dina Rae" }],
    album: {
      name: "The Eminem Show",
      images: [{ url: "/eminem-album-cover.jpg" }],
    },
    duration_ms: 350000,
    uri: "spotify:track:5",
    preview_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
    liked: true,
  },
  {
    id: "track6",
    name: "Yes",
    artists: [{ name: "LMFAO" }],
    album: {
      name: "Party Rock",
      images: [{ url: "/lmfao-party-rock-album.jpg" }],
    },
    duration_ms: 244000,
    uri: "spotify:track:6",
    preview_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
    liked: true,
  },
  {
    id: "track7",
    name: "Culichi",
    artists: [{ name: "Cartel De Santa" }],
    album: {
      name: "Cartel De Santa",
      images: [{ url: "/cartel-de-santa-album.jpg" }],
    },
    duration_ms: 245000,
    uri: "spotify:track:7",
    preview_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
    liked: false,
  },
  {
    id: "track8",
    name: "Everythanga Corrupt",
    artists: [{ name: "Ice Cube" }],
    album: {
      name: "Everythanga Corrupt",
      images: [{ url: "/ice-cube-album.jpg" }],
    },
    duration_ms: 268000,
    uri: "spotify:track:8",
    preview_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
    liked: false,
  },
  {
    id: "track9",
    name: "Symphony No. 5",
    artists: [{ name: "Ludwig van Beethoven" }],
    album: {
      name: "Beethoven's Best",
      images: [{ url: "/beethoven-piano.jpg" }],
    },
    duration_ms: 420000,
    uri: "spotify:track:9",
    preview_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
    liked: false,
  },
  {
    id: "track10",
    name: "Still D.R.E.",
    artists: [{ name: "Dr. Dre" }, { name: "Snoop Dogg" }],
    album: {
      name: "2001",
      images: [{ url: "/dr-dre-2001-album.jpg" }],
    },
    duration_ms: 271000,
    uri: "spotify:track:10",
    preview_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3",
    liked: false,
  },
  {
    id: "track11",
    name: "Paranoid",
    artists: [{ name: "Black Sabbath" }],
    album: {
      name: "Paranoid",
      images: [{ url: "/black-sabbath-paranoid-album-cover.jpg" }],
    },
    duration_ms: 170000,
    uri: "spotify:track:11",
    preview_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3",
    liked: false,
  },
  {
    id: "track12",
    name: "Party Rock Anthem",
    artists: [{ name: "LMFAO" }],
    album: {
      name: "Party Rock",
      images: [{ url: "/lmfao-party-rock-album.jpg" }],
    },
    duration_ms: 262000,
    uri: "spotify:track:12",
    preview_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3",
    liked: false,
  },
]

export const mockPodcasts = [
  {
    id: "podcast1",
    name: "Cómo contactar ángeles",
    description: "Video • Paranormal",
    images: [
      { url: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-uXaHleR2n56N2k48ODDMTiOM7eoyIa.png" },
    ],
    publisher: "Libro de Enoc",
    type: "podcast",
  },
  {
    id: "podcast2",
    name: "La Psicología del Éxito - Brian Tracy - Episodio 1 | 22",
    description: "Video • AudioCast 🎧 🔥",
    images: [
      { url: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-uXaHleR2n56N2k48ODDMTiOM7eoyIa.png" },
    ],
    publisher: "Brian Tracy",
    type: "podcast",
  },
  {
    id: "podcast3",
    name: "INCEL: LA IDEOLOGÍA QUE CONVIRTIÓ EL...",
    description: "Video • Perturba2",
    images: [
      { url: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-uXaHleR2n56N2k48ODDMTiOM7eoyIa.png" },
    ],
    publisher: "Perturba2",
    type: "podcast",
  },
  {
    id: "podcast4",
    name: "No Debí Cerrar tan TARDE | Relatos Paranormales d...",
    description: "Video • EXTRA ANORMAL",
    images: [
      { url: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-uXaHleR2n56N2k48ODDMTiOM7eoyIa.png" },
    ],
    publisher: "Extra Anormal",
    type: "podcast",
  },
]

export const mockCurrentTrack = mockTracks[0]

export const mockUserProfile = {
  id: "user1",
  display_name: "Christian Velasco",
  images: [{ url: "/placeholder.svg?height=100&width=100" }],
  email: "christian@example.com",
}
